#include "../include/se_fs_segy_header.h"


const segy_binhead_description_t segy_binhead_description = {
    "Job indentification number",
    "Line number",
    "Reel number",
    "Number of data traces per record",
    "Number of auxiliary traces per record",
    "Sample interval in microseconds (this reel)",
    "Sample interval in microseconds (field)",
    "Samples per trace (this reel)",
    "Samples per trace (field)",
    "Data sample format code",
    "CDP fold",
    "Trace sorting code (see below)",
    "Number of traces vertically summed",
    "Starting sweep frequency",
    "Ending sweep frequency",
    "Sweep length in milliseconds",
    "Sweep type code",
    "Trace number of sweep channel",
    "Sweep trace taper length at start (ms)",
    "Sweep trace taper length at end (ms)",
    "Taper type",
    "Correlated traces?        1=n 2=y",
    "Binary gain recovered?    1=y 2=n",
    "Amplitude recovery method",
    "Measurement system",
    "Impulse polarity",
    "Vibratory polarity code"
};

const segy_trchead_description_t segy_trchead_description = {
    "Trace number within line",
    "Trace # in reel OR Line # in 3D (nonstd)",
    "Original field record number",
    "Trace number within field record",
    "Energy source point number",
    "CDP ensemble number",
    "Trace number within CDP",
    "Trace identification code",
    "Number of vertically summed traces",
    "Number of horizontally summed traces",
    "Data use code 1=production 2=test",
    "Offset",
    "Group elevation",
    "Source elevation",
    "Source depth",
    "Datum elevation at group",
    "Datum elevation at source",
    "Water depth at source",
    "Water depth at group",
    "Scale factor for previous seven entries",
    "Scale factor for next four entries",
    "Source x",
    "Source y",
    "Group x",
    "Group y",
    "Coordinate units code",
    "Weathering velocity",
    "Subweathering velocity",
    "Source uphole time",
    "Group uphole time",
    "Source static",
    "Group static",
    "Total static",
    "Lag time A",
    "Lag time B",
    "Delay recording time",
    "Mute time start",
    "Mute time end",
    "Number of samples this trace",
    "Sample interval",
    "Gain type of field intstruments",
    "Instrument gain constant",
    "Instrument initial gain",
    "Correlated 1=no 2=yes",
    "Sweep start frequency",
    "Sweep end frequency",
    "Sweep length in ms",
    "Sweep type code",
    "Sweep trace length at start in ms",
    "Sweep trace length at end in ms",
    "Taper type",
    "Alias filter frequency if used",
    "Alias filter slope",
    "Notch filter frequency if used",
    "Notch filter slope",
    "Low cut frequency if used",
    "High cut frequency if used",
    "Low cut slope",
    "High cut slope",
    "Year data recorded",
    "Day of year",
    "Hour of day",
    "Minute of hour",
    "Second of minute",
    "Time basis code",
    "Trace weighting factor",
    "Group number of roll switch",
    "Group number of first trace in record",
    "Group number of last trace in record",
    "Gap size",
    "Overtravel taper code",
    "Crossline Number",
    "Inline Number",
    "Sample spacing between traces",
    "First trace location",
    "Negative of power used for dynamic range compression",
    "Reciprocal of scaling factor to normalize range",
    "Number of traces",
    "Mark selected traces"
};
